graphql-java-kickstart/graphql-java-servlet

src/main/java/graphql/servlet/GraphQLServlet.java
src/test/java/graphql/servlet/GraphQLServletTest.java

graphql-js, which is used by babel-relay-plugin, gives the following when the mutation object is empty:
> Error: mutation fields must be an object with field names as keys or a function which returns such an object.

Omit mutation object when there are no mutations

---

build.gradle
src/main/java/graphql/servlet/GraphQLServlet.java

Hello,
This pull request contains a few changes I made to be able to use this project in our of our products. 
- Quick correction in the build.gradle file where the groupId in MyPublication was still the old one
- Downgraded the Servlet API version from 3.1.0 to 3.0.1 because our application platform only support 3.0 for the time being and I couldn't identify a strong need to use version 3.1 in the servlet (unless I missed something ?)
- Made the service references for the context and execution strategy providers optional as they do have default implementations.
I hope these changes will be useful and may be accepted back into the project. If not please don't hesitate to comment on this PR I will do my best to address any issues or questions.
Best regards,
Serge Huber.

Servlet API downgrade, correction in groupId and made some service references optional

---

build.gradle
src/main/java/graphql/servlet/GraphQLServlet.java

This pull request contains the following modifications and fixes : 
- Update graphql-java to 2.1.0 to get support of directive locations
- Update graphql-java-annotations to 0.11.0
- Fix minor typo in project description
- Modify variables setter to use JSON format instead of string forma as is now documented in the latest specification here : http://graphql.org/learn/serving-over-http/#post-request . This change is also now done on GraphiQL : graphql/graphiql#168
- Add support for GET parameters (query and variables) as is also specified here : http://graphql.org/learn/serving-over-http/#get-request
- Fix some NPEs when no parameters where specified.
All these changes have been tested against the latest master branch of GraphiQL.

Specification updates

---

src/main/java/graphql/servlet/GraphQLServlet.java

Add support for operationName that was not implemented. We can now build GraphQL code such as : 
```
query UserQuery {
dx {
user(userKey: "root") {
id
properties {
key
value
}
}
}
}
mutation CreateNode {
createNodeByPath(name:"test", parentPath: "/") {
identifier
path
parentIdentifier
}
}
```
And choose which operation to execute using GraphiQL's play button.

Add support for operationName that was not implemented

---

src/main/java/graphql/servlet/GraphQLServlet.java

JSON is unicode, but if no charset is specified, ISO-8859-1 will be used
by servlet containers.

Use charset UTF-8 for JSON responses

---

src/main/java/graphql/servlet/GraphQLServlet.java
src/main/java/graphql/servlet/GraphQLTypesProvider.java

An implementation of GraphQLTypesProvider can provide a list of types, which will be passed to the schema when initializing it. This is particularily useful when using GraphQL Interfaces, as types implementing the interfaces may not appear in the query types tree.

Added support for initial types dictionnary

---

.gitignore
build.gradle
src/test/java/graphql/servlet/GraphQLVariablesTest.java

Update version of graphql-java from 2.2.0 to 2.3.0 and fix tests

---

gradle.properties
src/main/java/graphql/servlet/GraphQLOperationListener.java
src/main/java/graphql/servlet/GraphQLServlet.java
src/main/java/graphql/servlet/OsgiGraphQLServlet.java
src/main/java/graphql/servlet/SimpleGraphQLServlet.java
src/test/java/graphql/servlet/GraphQLServletTest.java
src/test/java/graphql/servlet/GraphQLVariablesTest.java

This pull creates an abstract parent with the barebones "meat and potatoes" of the servlet.  This makes the project fully extensible, allowing for custom implementations without copy/paste.
This is a refinement of #14, chosen over the approach of #15 for reasons listed in that PR.

Extract base functionality into abstract parent

---

src/main/java/graphql/servlet/OsgiGraphQLServlet.java

Hello, 
I was testing the OSGi servlet with Apache Karaf 4.1.1 and it was not working. I saw that the component was not being properly registered as a HttpServlet service so I added an explicit service class registration which fixed the problem.

Fix OSGi service registration

---

src/main/java/graphql/servlet/GraphQLQueryProvider.java
src/main/java/graphql/servlet/OsgiGraphQLServlet.java
src/test/groovy/graphql/servlet/GraphQLVariablesSpec.groovy
src/test/groovy/graphql/servlet/OsgiGraphQLServletSpec.groovy

Hello,
I'd like to propose the following changes: 
- Renaming the root query and mutation types from "query" and "mutation" to "Query" and "Mutation" to follow object type naming conventions
- Modified the GraphQLQueryProvider implementation to make the old API deprecated and replace with a collection of field definitions, making this aligned with the GraphQLMutationProvider interface. This makes it possible to define data fetcher for the root object type fields.
- Added JavaDoc documentation to the GraphQLQueryProvider interface
I think these changes would make the exposed GraphQL API a lot cleaner and also a lot more flexible. The inability to use data fetchers on the fields or list types in the root object types is a very strong limitation.
If these changes are approved I'd be willing …

Root type name changes & query provider API changes

---

src/main/java/graphql/servlet/GraphQLServlet.java
src/main/java/graphql/servlet/InstrumentationProvider.java
src/main/java/graphql/servlet/NoOpInstrumentationProvider.java
src/main/java/graphql/servlet/NoopInstrumentationProvider.java
src/main/java/graphql/servlet/OsgiGraphQLServlet.java
src/main/java/graphql/servlet/SimpleGraphQLServlet.java

This is a quick and dirty to add extensibility for instrumentation.
Not sure if this is all that needs to be done.
All tests still seem to pass.

Added support for instrumentation

---

src/main/java/graphql/servlet/OsgiGraphQLServlet.java

If references are not as greedy, activating a bundle with an ExecutionStrategyProvider / InstrumentationProvider / GraphQLErrorHandler will be ignored. Since these services are used at each query and do not impact the schema creation, it is also possible to set them as dynamic to avoid a restart of the bundle.

Make references dynamic/greedy to take new services into account

---

src/main/java/graphql/servlet/DefaultGraphQLErrorHandler.java
src/test/groovy/graphql/servlet/GraphQLServletSpec.groovy
src/test/groovy/graphql/servlet/TestGraphQLErrorException.groovy

According to the `graphql-java` documentation, ["Error while fetching data"](https://graphql-java.readthedocs.io/en/v6/execution.html#exceptions-while-fetching-data), it says:
> If the exception you throw is itself a GraphqlError then it will transfer the message and custom extensions attributes from that exception into the ExceptionWhileDataFetching object. This allows you to place your own custom attributes into the graphql error that is sent back to the caller.
In `graphql.execution.SimpleDataFetcherExceptionHandler`, all exceptions are wrapped in a `graphql.ExceptionWhileDataFetching`. To maintain the functionality as described in the `graphql-java`-docs we need to check if the inner exception in `graphql.servlet.DefaultGraphQLErrorHandler.java:47` is of type `GraphQLError`, in which …

Check if inner exception is of type GraphQLError in DefaultGraphQLErrorHandler

---

src/main/java/graphql/servlet/GraphQLServlet.java
src/main/java/graphql/servlet/GraphQLServletListener.java

The [GraphQL spec](http://facebook.github.io/graphql/October2016/#sec-Response-Format) mentions an `extensions` entry in the response map that implementors can use to provide additional information for a GraphQL request.  For instance, the [TracingInstrumentation](graphql-java/src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java) will capture tracing information and populate the extensions field on the ExecutionResult.  This change passes along the `extensions` from the `ExecutionResult` (if any exist).

Add extensions to the response map as per the spec

---

src/main/java/graphql/servlet/SimpleGraphQLServlet.java

I have servlet which extends `SimpleGraphQLServlet`. After recent change which added builder all `SimpleGraphQLServlet` constructors are either deprecated or not accessible. This PR makes the new constructor with builder accessible to derived classes.

SimpleGraphQLServlet: protected constructor with Builder

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/graphql/servlet/NoOpInstrumentationProvider.java
src/main/java/graphql/servlet/SimpleGraphQLServlet.java
src/test/groovy/graphql/servlet/OsgiGraphQLServletSpec.groovy

- Fix issue with the missing "NoOpInstrumentation"
- Update the test dependency on the graphql annotations to fix
issue with the OSGI test

Update to work with graphql-java 8.0

---

src/main/java/graphql/servlet/GraphQLServlet.java
src/test/groovy/graphql/servlet/GraphQLServletSpec.groovy

Simple change to ensure that the readlimit passed into InputStream.mark matches the length of the read buffer. This ensures that when InputStream.reset is called the stream is reset correctly. A test has also been added to ensure this behaviour.
The reason for this pull request is outlined in the [issue #61](https://github.com/graphql-java/graphql-java-servlet/issues/61).

Changes to look ahead in isBatchedQuery

---

src/main/java/graphql/servlet/GraphQLServlet.java
src/test/groovy/graphql/servlet/GraphQLServletSpec.groovy

as mentioned in https://graphql.org/learn/serving-over-http/#post-request

Add support for application/graphql content-type

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/main/java/graphql/servlet/ApolloScalars.java
src/main/java/graphql/servlet/GraphQLObjectMapper.java
src/main/java/graphql/servlet/internal/VariableMapper.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy
src/test/groovy/graphql/servlet/TestUtils.groovy

This will allow the https://github.com/jaydenseric/graphql-multipart-request-spec
to be supported. [Apollo File Uploads](https://www.apollographql.com/docs/guides/file-uploads.html) are built on top of this.

Add support for an 'operations' part when doing a multipart POST.

---

src/main/java/graphql/servlet/ApolloSubscriptionConnectionListener.java
src/main/java/graphql/servlet/DefaultGraphQLContextBuilder.java
src/main/java/graphql/servlet/GraphQLContext.java
src/main/java/graphql/servlet/GraphQLContextBuilder.java
src/main/java/graphql/servlet/GraphQLInvocationInputFactory.java
src/main/java/graphql/servlet/GraphQLWebsocketServlet.java
src/main/java/graphql/servlet/SubscriptionConnectionListener.java
src/main/java/graphql/servlet/internal/ApolloSubscriptionProtocolHandler.java
src/main/java/graphql/servlet/internal/SubscriptionHandlerInput.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy

Introduced a `ConnectionSubscriptionListener` that provides the ability to handle the `onConnect`. See also: https://www.apollographql.com/docs/graphql-subscriptions/authentication.html.
If `onConnect` returns an `Object` it is set in the `Session.userProperties`, which in turn is used now when building the `GraphQLContext`. It's currently available through `GraphQLContext.getConnectResult()`. 
`GraphQLContext` could be improved by splitting it up in separate context implementations instead of this version, but left that for a different case.
The default implementation provided here does nothing. If you want to add authorization using these features you would have to provide an implementation of `ApolloSubscriptionConnectionListener` that would handle the authorization and throws a …

Handle Apollo subscription onConnect

---

src/main/java/graphql/servlet/GraphQLQueryInvoker.java

@marshi
This allows you to configure the options you want to use when constructing a `DataLoaderDispatcherInstrumentation`:
```java
GraphQLQueryInvoker.newBuilder().
.withDataLoaderDispatcherInstrumentationOptions(DataLoaderDispatcherInstrumentationOptions.newOptions().includeStatistics(true))
.build();
```
These options are then used here:
```java
protected Instrumentation getInstrumentation(Object context) {
if (context instanceof GraphQLContext) {
return ((GraphQLContext) context).getDataLoaderRegistry()
.map(registry -> {
List<Instrumentation> instrumentations = new ArrayList<>();
instrumentations.add(getInstrumentation.get());
instrumentations.add(new DataLoaderDispatcherInstrumentation(registry, dataLoaderDispatcherInstrumentationOptionsSupplier.get()));
return new …
```

Added supplier for DataLoaderDispatcherInstrumentationOptions (fix #98)

---

build.gradle
examples/osgi/apache-karaf-feature/pom.xml
examples/osgi/apache-karaf-package/pom.xml
examples/osgi/pom.xml
examples/osgi/providers/pom.xml

Here are various changes I had to make.
For me, jackson 2.8.11.1 couldn't be found in https://repo.maven.apache.org/maven2, 
so I downgraded it to 2.8.11.
I changed the group IDs of the example artifacts to com.graphql-java-kickstart from
com.graphql-java to match the main artifacts
I added slf4j to the feature. This now seems to be required.
There now seems to be an incompatibility between the karaf maven plugin and the latest
maven-install-plugin:3.0.0-M1. See https://stackoverflow.com/a/52622275/518627. So I
put in specific references to the previous plugin versions in order to fix this.
The change that *actually* makes the result work is to change
the dependency on javax-servlet-api to be 3.1.0 in the build.gradle
file. Otherwise the graphql-java-servlet depends on javax-servlet-api …

Attempt to make the OSGi example work with the latest version of graphql-java-servlet

---

src/main/java/graphql/servlet/OsgiGraphQLHttpServlet.java

Allow the ability to delay the update of the schema through a config
option. By default this is 0, leaving the behaviour unchanged, and no
penalty is paid.
If the delay is set to a non zero value, it only updates the schema if no
changes to the whiteboard have happened within that delay timeout.
Also fixed up a couple of things with the whiteboard. Using
policy=DYNAMIC is the normal approach, the component can activate
and gets references added as appropriate. The "typesProviders" method
was in error as the name didn't match the unbind. I believe that what
was happenning before is that the component was being activated
and deactivated each time a new reference was added. Now it's activated
once and the whiteboard works correctly.
Note that my preference would be to set the default delay …

Improve schema OSGi whiteboard update performance by batching

---

gradle.properties
src/main/java/graphql/servlet/GraphQLInvocationInput.java
src/main/java/graphql/servlet/GraphQLQueryInvoker.java
src/main/java/graphql/servlet/GraphQLSchemaProvider.java
src/main/java/graphql/servlet/OsgiGraphQLHttpServlet.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy

Upgraded graphql-java version to 11.0 and reworked `DataLoaderRegistry`. See https://github.com/graphql-java/graphql-java/releases/tag/v11.0 for further details from the graphql-java side. The way to use data loaders with graphql-java-servlet doesn't change with this update.

Upgrade graphql-java to 11.0

---

src/main/java/graphql/servlet/GraphQLWebsocketServlet.java
src/main/java/graphql/servlet/internal/WsSessionSubscriptions.java

Similarly to graphql-java-kickstart/graphql-java-servlet#124, adds a method to able to grab the total number of active subscriptions.
Hope to use this with a MeterBinder in a Spring application for metrics.

Method for requesting number of subscriptions

---

src/main/java/graphql/servlet/GraphQLObjectMapper.java

Currently, the object mapper created using `ObjectMapperProvider` & `ObjectMapperConfigurer` is unchanged before use. This includes the default property inclusion value of the `ObjectMapper`. It would never make sense to not have this value be anything other than `JsonInclude.Include.ALWAYS` since GraphQL query results are never to omit any requested property regardless of the value of the property.
In a project where both RESTful endpoints and GraphQL are used, the situation may arise where the RESTful endpoints are to omit properties from responses under certain conditions (e.g. omit all `null` values from the response). When this is the case and the project uses the same `ObjectMapper` for both the RESTful endpoints and the `GraphQLServlet`, then it would be most helpful to "ignore" …

Jackson mapper default property inclusion should be "ALWAYS" to prevent null values from being omitted in query results

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy
src/test/groovy/graphql/servlet/TestInstrumentation.java
src/test/groovy/graphql/servlet/TestUtils.groovy

Abstract servlet does not maintain the http request for the application/graphql content type path of the post handler - this adds it in. The tests verify in a similar fashion to our use case.

Abstract servlet does not maintain http request data for application/graphql

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/main/java/graphql/servlet/GraphQLConfiguration.java
src/main/java/graphql/servlet/internal/GraphQLThreadFactory.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy
src/test/groovy/graphql/servlet/TestUtils.groovy

When using servlet in async mode, a [new thread is created for every request](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java#L295).  The purpose of this pull request is to improve performance by using a ThreadPoolExecutor so threads will be reused.

Use thread pool executor for async queries

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/main/java/graphql/servlet/BatchExecutionHandler.java
src/main/java/graphql/servlet/DefaultBatchExecutionHandler.java
src/main/java/graphql/servlet/GraphQLQueryInvoker.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy
src/test/groovy/graphql/servlet/TestBatchExecutionHandler.java

@oliemansm, another minor change - we found if we throw an exception the server will return 400, but if we try to write any sort of error message tomcat will not update the status preventing us from sending back 400 with any sort of message

Allow batch handler to set http status

---

src/main/java/graphql/servlet/GraphQLObjectMapper.java

[In the official GraphQL spec, it says the following](https://facebook.github.io/graphql/June2018/#sec-Response-Format):
> When `errors` is present in the response, it may be helpful for it to appear first when serialized to make it more clear when errors are present in a response during debugging.
In my own personal debugging, I've found that my teammates and I often overlook `errors` because the property is located after `data`. The same goes for `extensions`. This pull request changes the response message property order to the following:
- `errors`
- `extensions`
- `data`

Reordered properties in JSON response according to recommendation in GraphQL spec

---

src/main/java/graphql/servlet/internal/GraphQLRequest.java

Fix an issue with graphql-java 12, where passing a GraphQL requests with variables=null would result in an exception

Ensure 'variables' is never null, since graphql-java 12.0 expects it

---

gradle.properties

Fixes #159 
https://github.com/graphql-java/graphql-java/releases/tag/v12.0

Upgrade to graphql-java v12.0

---

src/main/java/graphql/servlet/ConfiguringObjectMapperProvider.java
src/main/java/graphql/servlet/internal/VariablesDeserializer.java

#177 Avoid explicitly inject ObjectMapper to the ObjectMapper

---

src/main/java/graphql/servlet/ConfiguringObjectMapperProvider.java
src/main/java/graphql/servlet/DefaultObjectMapperConfigurer.java
src/main/java/graphql/servlet/GraphQLObjectMapper.java
src/main/java/graphql/servlet/internal/VariablesDeserializer.java

Provide ability to plug in pre configured objectmapper

---

src/main/java/graphql/servlet/GraphQLSchemaProvider.java

Fixes support for the code registry (as opposed to type resolvers & data fetchers attached directly to schema objects).
```
Caused by: graphql.AssertException: There must be a type resolver for union ExampleUnion
at graphql.Assert.assertNotNull(Assert.java:15) ~[graphql-java-12.0.jar:na]
[…]
at graphql.schema.GraphQLCodeRegistry$Builder.getTypeResolver(GraphQLCodeRegistry.java:230) ~[graphql-java-12.0.jar:na]
[…]
at graphql.schema.SchemaUtil.extractCodeFromTypes(SchemaUtil.java:112) ~[graphql-java-12.0.jar:na]
[…]
at graphql.schema.GraphQLCodeRegistry.transform(GraphQLCodeRegistry.java:139) ~[graphql-java-12.0.jar:na]
at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:413) ~[graphql-java-12.0.jar:na]
at graphql.servlet.GraphQLSchemaProvider.copyReadOnly(GraphQLSchemaProvider. …
```

GraphQLSchemaProvider#copyReadOnly: simpler, supports CodeRegistry

---

src/main/java/graphql/servlet/DefaultGraphQLErrorHandler.java

Separated out logging of errors to separate overriddable method in DefaultGraphQLErrorHandler so that entire processErrors method does not need to be overridden just to change which errors get logged by users of DefaultGraphQLErrorHandler.
When a user of this library wants to override DefaultGraphQLErrorHandler to create their own but retain the functionality of DefaultGraphQLErrorHandler without copying the code, that user cannot change which errors are logged unless they reimplement the entire processErrors method. This PR separates out the logging of errors into a separate method that can be overridden to prevent the need to reimplement all of processErrors just to change which errors are logged.

separated out logging of errors to separate overriddable method in DefaultGraphQLErrorHandler

---

build.gradle
src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/main/java/graphql/servlet/core/GraphQLObjectMapper.java
src/test/groovy/graphql/servlet/AbstractGraphQLHttpServletSpec.groovy
src/test/groovy/graphql/servlet/TestUtils.groovy

An initial attempt at adding `@defer` directive support #133. Similar to the [apollo spec](https://github.com/apollographql/apollo-server/blob/defer-support/docs/source/defer-support.md), although currently without the specified line ending `CRLF + "-----" + CRLF `. I still have to integration test this.
1. [GraphQLJava @defer example](https://github.com/graphql-java/graphql-java-examples/blob/master/defer/server/src/main/java/com/graphqljava/defer/GraphQLController.java#L104)

Defer support

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java

Fix #205 java.io.IOException: Mark not set

---

src/main/java/graphql/servlet/OsgiGraphQLHttpServlet.java
src/main/java/graphql/servlet/config/GraphQLCodeRegistryProvider.java
src/test/groovy/graphql/servlet/OsgiGraphQLHttpServletSpec.groovy

Provide a fix for the reported issue #207

Fix #207 added CodeRegistry provider for Osgi servlet

---

src/main/java/graphql/servlet/AbstractGraphQLHttpServlet.java
src/main/java/graphql/servlet/core/GraphQLObjectMapper.java

I checked this improvement using this test `customers` query https://github.com/shailender-bathula/samples/commit/fd1bf6d64aa5a087ad81293b5d94b64234028ba1 and [bombardier](https://github.com/codesenberg/bombardier) HTTP benchmarking tool.
I ran the application using the default settings i.e. `../gradlew appRun` and benchmarking like this:
`bombardier --method POST --header "Content-Type: application/json" --duration=70s --connections=110 --body '{ "query": "{ customers {id firstName lastName yearOfBirth email} }" }' http://localhost:8080/servlet-hello-world/graphql`
There was an improvement of 5 - 10 requests/second before and after in those tests. The difference may be more in higher throughput environments.

Serialize query response directly to Servlet's output stream to avoid intermediate String object creation

---

graphql-java-servlet/build.gradle

Guava is a dangerous dependency to bring in for a framework. Guava is very version specific, and will easily conflict with other versions of guava brought in by an application. Generally it's better to not depend on Guava for frameworks/libraries.
It seems guava is actually only used in tests, which is great! I moved the dependency to be a test dependency only, so it will no longer pollute the classpath of applications using graphql-java-servlet.

Move guava dependency to testCompile

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/BatchedQueryResponseWriter.java
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/AbstractGraphQLHttpServletSpec.groovy

Related to https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/220 but for batched queries
Also updated the tests to check contentLength accordingly.

fix content length on batched queries

---

graphql-java-kickstart/bnd.bnd
graphql-java-kickstart/build.gradle
graphql-java-servlet/bnd.bnd
graphql-java-servlet/build.gradle

When the servlet bundle is loaded in an OSGi environment it is missing the kickstart packages, however the kickstart JAR doesn't include OSGi metadata. This PR provides a fix.
Also the BND config was externalised from the gradle script for easier management.

Added OSGi metadata to kickstart artefact

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/BatchedQueryResponseWriter.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/SingleQueryResponseWriter.java
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/SingleQueryResponseWriterTest.groovy

The recent changes on `setContentLength` broke some spring-security functionality as spring-security recalculates `content-length` when `getWriter().write(String)` is called to check if the response is completed.
Therefore the session cookie will only be set after everything is over and the response was already sent back to the client.
Here's where this happens: [OnCommittedResponseWrapper.java](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java#L222)
I think that using the same byte array used to set the `content-length` is the most secure way to avoid problems like this.
I also changed the test, but not sure if it was the correct approach.

writing content as bytes to avoid contentLength calculation problems

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/config/DefaultExecutionStrategyProvider.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/config/GraphQLBuilder.java

Allowing null values to be passed into DefaultExecutionStrategyProvider because graphql-java handles null values and uses defaults when null execution strategies are given, so there is no longer a need to have default values set in this library.
Here you will find the code that sets the default execution strategies in graphql-java: https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphQL.java#L180-L182

Allow null values in DefaultExecutionStrategyProvider

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/GraphQLSubscriptionMapper.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/apollo/SubscriptionStartCommand.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/subscriptions/FallbackSubscriptionConsumer.java

Fixes the following error while subscription request deserialization:
```
2020-05-04 21:46:34:935 [https-jsse-nio-8079-exec-7] ERROR g.k.servlet.GraphQLWebsocketServlet - Error executing websocket query for session: 0
java.lang.IllegalArgumentException: Cannot construct instance of `graphql.kickstart.execution.GraphQLRequest` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"query":"subscription Logs { logs(eventId: \"87654\") { id } }"}')
at [Source: UNKNOWN; line: -1, column: -1]
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3938)
at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3869)
at graphql.kickstart.execution.subscriptions.GraphQLSubscriptionMapper.readG …
```

Fix Subscription GraphQLRequest deserialization

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/GraphQLInvoker.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/AbstractGraphQLHttpServlet.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/GraphQLConfiguration.java

@kclaes Took awhile, but finally found a bit of time for it. Can you take a look if this will do?

Allow async timeout to be configured #184

---

graphql-java-servlet/bnd.bnd

@oliemansm 
Hello again, sry that i haven't been responsive lately after the last pull request.
Work got chaotic after the COVID situation.
I would like to present a more immediate fix to the underlying problem in this pull request.
The goal of this PR is not to make the project itself into modules, but rather to make it compatible with the module system.
Projects that are not made into modules can still be used by modules because they will normally be converted into automatic modules.
With graphql-java-servlet this is not possible (atleast not without heavy configuration) because of the overlapping classes/packages in the jar files that throw this process off.
https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/244
I go into details here on how the problem looks like with …

Exclude overlap in dependency jars

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/GraphQLObjectMapper.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/BatchedQueryResponseWriter.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/SingleQueryResponseWriter.java
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/BatchedQueryResponseWriterTest.groovy

Optimize single & batch query response writers to reduce memory allocation overhead caused by the servlet.
When large 10MiB+ responses are serialized, existing implementation performs significant amount of redundant string conversions and string concatenations. In my scenario overhead reached as much as 4GiB in extra RAM allocated.
This change replaces Json serialization into a String with Json serialization into byte array for both single and batch queries. In addition, it removes all string concatenations from batch response writer.

Optimize single & batch query response writers to reduce memory allocation overhead

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/AsyncTaskDecorator.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/AsyncTaskExecutor.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/GraphQLConfiguration.java

Support async task decorator

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvokerImpl.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/ListenerHandler.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/core/GraphQLServletListener.java

Hello!
This PR adds a small but quite useful feature, it modifies the original `GraphQLServletListener` by adding an additional method `void beforeFlush(HttpServletRequest request, HttpServletResponse response)`, which will be called right before the response will be written and flushed. 
In our use-case it can be used to add headers like `API rate limit` or some temporal tokens generated after some GraphQL mutations were called together.

Added an ability to add headers before writing GraphQL response.

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/SubscriptionProtocolFactory.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/apollo/ApolloSubscriptionConnectionListener.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/apollo/ApolloSubscriptionKeepAliveRunner.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/apollo/ApolloSubscriptionProtocolFactory.java
graphql-java-kickstart/src/main/java/graphql/kickstart/execution/subscriptions/apollo/KeepAliveSubscriptionConnectionListener.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/GraphQLWebsocketServlet.java

Hi,
I ran into different issues when trying to use GraphQLWebsocketServlet within an OSGi container :
The first issue (which should also happen in any container) is about the executor started in ApolloSubscriptionKeepAliveRunner, which is never shut down, preventing the JVM to correctly quit. I've added shutdown callbacks in SubscriptionProtocolFactory / ApolloSubscriptionConnectionListener / ApolloSubscriptionKeepAliveRunner
Second issue is the GraphQLWebsocketServlet initialization - there's no way to pass explicit SubscriptionProtocolFactory, and prevent the creation of default instances, which was required in our case.

Shutdown executor and provide new endpoint constructor

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/input/GraphQLSingleInvocationInput.java

A possible change to the GraphQLSingleInvocationInput that will help support the new context in alignment with graphql-java-tools.
See:
https://github.com/graphql-java-kickstart/graphql-java-tools/pull/566

bug fix 393

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvokerImpl.java

Add exception handling for synchronous execution

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestHandlerImpl.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvoker.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvokerImpl.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/InvocationInputParseException.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/ListenerHandler.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/cache/CachingHttpRequestInvoker.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/core/GraphQLServletListener.java
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/AbstractGraphQLHttpServletSpec.groovy
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/cache/CachingHttpRequestInvokerTest.groovy

As described in #417, we cannot handle the error when creating an`InvocationInput` with a servlet request.
- Change `ListenerHandler` creation location.
- Add `InvocationInputParseException` to isolate exception to parsing.
- Add `onParseError(...)` to `RequestCallback` interface and call it when `InvocationInputParseException` occurs.
- Fix related tests.
Closes #417

Add listener for errors that occur in parsing `InvocationInput`

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvokerImpl.java

Hello!
We just upgraded to the latest version of https://github.com/graphql-java-kickstart/graphql-spring-boot/releases/tag/v13.0.0. And found that all of our tests failed.
The reason because we are not using a sync servlet, but our GraphQL partially uses common ForkJoinPool for fetching fields and the result is that the current HttpRequestInvokerImpl is not waiting for the result to be loaded.

For non-async servlet wait until GraphQL async operation finished.

---

gradle/wrapper/gradle-wrapper.properties
graphql-java-servlet/build.gradle

- Replaced cglib with byte-buddy since cglib is deprecated
- Updated gradle version to 8.5
With these two bumps the build does not fail anymore

chore(deps): replace cglib with byte-buddy

---

graphql-java-servlet/src/main/java/graphql/kickstart/servlet/OsgiGraphQLHttpServlet.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/OsgiSchemaBuilder.java
graphql-java-servlet/src/main/java/graphql/kickstart/servlet/osgi/GraphQLDirectiveProvider.java
graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/OsgiGraphQLHttpServletSpec.groovy

Recreated from https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/557
https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions/555
Currently graphql schema with custom directives can fail validation due to missing custom directive definitions when trying to build the schema.
Add new GraphQLDirectiveProvider to be able to insert these custom directive definitions and build/validate schema without issues.

Add new GraphQLDirectiveProvider for custom directives

---

graphql-java-kickstart/src/main/java/graphql/kickstart/execution/error/DefaultGraphQLServletObjectMapperConfigurer.java

Since the project now runs on java >= 11 and uses the latest jackson version, it is no longer necessary to register this module because it is included in jackson-databind.
Refs: #570

fix: remove Jdk8Module Jackson module registration
